### ISSUE TITLE
Recommended parameter values + support for long reads

### ISSUE THREAD

**Issue by bcpd** [KoslickiLab/fmh-funprofiler#6]
I am interested in testing `funpfrofiler` for long reads (Nanopore; ~Q20+ chemistry). I have paired QCd Illumina data (which were also used for reconstructing high quality MAGs) as a comparator. In the biorxiv paper, Illumina data were analyzed with parameters -k 11 and --threshold-bp 500 (if I understood correctly). Would these parameter values be reasonable in general? And if so, should they be used to guide analysis of Nanopore data?

Thanks!

**Comment by bcpd** [comment]
Hi all -- it appears as though Nanopore reads produce results that are comparable to Illumina's. I did not find an appreciable difference between -k 11 and 15. Any other recommendation for Nanopore data would be appreciated.

Thanks very much,
Pedro.

**Comment by mahmudhera** [comment]
Sorry for the late response. 

In theory, the pipeline should work for long/short reads the same way, because it works by extracting kmers.  In general, longer k values are highly sensitive to mutations/errors. It is not objectively correct to say that smaller k values are preferred, but if you did not see any difference between 11 and 15, I would prefer to use 11.

For the threshold bp: if you want "more" matches to have better completeness (with the risk of larger number of false positives) -- you can use a smaller threshold bp. In our experiments (on Illumina reads), we found 500 to be a good balance between completeness and purity. On Nanopore data, my hypothesis is that it would be worse to use a lower threshold because of a higher error rate (resulting in more false positives), but I do not have any experimental results to support my hypothesis.

Let us know if you need any more help (and reopen the issue in that case).
